"""Shared utilities available to both Jetson and PC processes."""

from .camera import (
    CameraIntrinsics,
    CameraIntrinsicsConfigError,
    focal_lengths_from_fov,
)
from .control import (
    AxisPair,
    ControlConfig,
    ControlConfigError,
    LaserAimingControlConfig,
    LaserConfigError,
    LaserMountConfig,
    LaserRenderConfig,
    PredictionConfig,
    Vector3,
    angular_error_from_pixel_delta,
    angular_error_from_pixels,
    pixel_error,
    pixel_delta,
)
from .geometry import (
    intersect_ray_with_depth,
    laser_ray_to_pixel,
    pixel_to_camera_ray,
    project_point_to_pixel,
)
from .ranging import (
    KnownSizeRangingConfig,
    KnownSizeRangingConfigError,
    DistanceEstimate,
    RangingCandidate,
    compute_distance_estimate,
    iter_distance_estimates,
    iter_ranging_candidates,
    normalized_box_dimensions,
    resolve_class_label,
)
from .schemas import (
    Box,
    CamState,
    ControlCmd,
    DetectionMsg,
    detection_msg_from_json,
    detection_msg_to_json,
)

__all__ = [
    "CameraIntrinsics",
    "CameraIntrinsicsConfigError",
    "AxisPair",
    "ControlConfig",
    "ControlConfigError",
    "LaserAimingControlConfig",
    "LaserConfigError",
    "LaserMountConfig",
    "LaserRenderConfig",
    "PredictionConfig",
    "Vector3",
    "angular_error_from_pixel_delta",
    "angular_error_from_pixels",
    "focal_lengths_from_fov",
    "intersect_ray_with_depth",
    "KnownSizeRangingConfig",
    "KnownSizeRangingConfigError",
    "DistanceEstimate",
    "RangingCandidate",
    "compute_distance_estimate",
    "iter_distance_estimates",
    "iter_ranging_candidates",
    "normalized_box_dimensions",
    "resolve_class_label",
    "laser_ray_to_pixel",
    "pixel_delta",
    "pixel_error",
    "pixel_to_camera_ray",
    "project_point_to_pixel",
    "Box",
    "CamState",
    "ControlCmd",
    "DetectionMsg",
    "detection_msg_from_json",
    "detection_msg_to_json",
]
